/* CobolCompiler.java */
/* Generated By:JavaCC: Do not edit this line. CobolCompiler.java */
import java.io.*;

public class CobolCompiler implements CobolCompilerConstants {

  java.util.List<String> codigo = new java.util.ArrayList<>();
  int contadorEtiquetas = 0;

  String nuevaEtiqueta() {
    return "LBL" + (contadorEtiquetas++);
  }

  void emitir(String instruccion) {
    codigo.add(instruccion);
  }

  void mostrarCodigo() {
    System.out.println("=== Codigo intermedio generado ===");
    for (String inst : codigo) {
      System.out.println(inst);
    }
  }

  public static void main(String args[]) throws Exception {
    InputStream entrada = System.in;

    if (args.length > 0) {
      entrada = new FileInputStream(args[0]);
    }

    CobolCompiler miParser = new CobolCompiler(entrada);
    miParser.programa();
    System.out.println("\u00a1El programa se analizo correctamente!");
  }

/*
 * SECCION DE GRAMATICA
 */
  final public 
void programa() throws ParseException {
    jj_consume_token(PROGRAMA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    case NUMERO:{
      jj_consume_token(NUMERO);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(PUNTO);
    jj_consume_token(INICIO);
    sentencias();
    jj_consume_token(FIN);
    jj_consume_token(PUNTO);
    jj_consume_token(0);
mostrarCodigo();
}

  final public void sentencias() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MUEVE:
      case LEE:
      case MUESTRA:
      case SUMA:
      case RESTA:
      case DANDO:
      case CALCULA:
      case SI:
      case EJECUTA:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      sentencia();
    }
}

  final public void sentencia() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEE:
    case MUESTRA:
    case DANDO:{
      instruccionIO();
      break;
      }
    case MUEVE:
    case SUMA:
    case RESTA:
    case CALCULA:{
      instruccionAsignar();
      break;
      }
    case SI:{
      instruccionComparar();
      break;
      }
    case EJECUTA:{
      instruccionBucle();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void instruccionIO() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MUESTRA:{
      jj_consume_token(MUESTRA);
      listaLiterales();
      jj_consume_token(PUNTO);
emitir("print " + getToken(0).image);
      break;
      }
    case LEE:{
      jj_consume_token(LEE);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PUNTO);
emitir("lee " + getToken(1).image);
      break;
      }
    case DANDO:{
      jj_consume_token(DANDO);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PUNTO);
emitir("valord " + getToken(1).image);
      emitir("print " + getToken(1).image);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void listaLiterales() throws ParseException {
    literal();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMA);
      literal();
    }
}

  final public void literal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CADENA_DOBLE:{
      jj_consume_token(CADENA_DOBLE);
emitir("metecad " + token.image);
      break;
      }
    case CADENA_SIMPLE:{
      jj_consume_token(CADENA_SIMPLE);
emitir("metecad " + token.image);
      break;
      }
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
emitir("valord " + token.image);
      break;
      }
    case NUMERO:{
      jj_consume_token(NUMERO);
emitir("mete " + token.image);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void instruccionAsignar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MUEVE:{
      jj_consume_token(MUEVE);
      valor();
      jj_consume_token(A);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PUNTO);
emitir("valori " + getToken(3).image);
      emitir("swap");
      emitir("asigna");
      break;
      }
    case SUMA:{
      jj_consume_token(SUMA);
      valor();
      jj_consume_token(A);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PUNTO);
emitir("valord " + getToken(3).image);
      emitir("add");
      emitir("valori " + getToken(3).image);
      emitir("swap");
      emitir("asigna");
      break;
      }
    case RESTA:{
      jj_consume_token(RESTA);
      valor();
      jj_consume_token(A);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PUNTO);
emitir("valord " + getToken(3).image);
      emitir("swap");
      emitir("sub");
      emitir("valori " + getToken(3).image);
      emitir("swap");
      emitir("asigna");
      break;
      }
    case CALCULA:{
      jj_consume_token(CALCULA);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL_ASIGN);
      expresion();
      jj_consume_token(FIN_CALCULA);
      jj_consume_token(PUNTO);
emitir("valori " + getToken(1).image);
      emitir("swap");
      emitir("asigna");
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void listaValores() throws ParseException {
    valor();
    valor();
}

  final public void valor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO:{
      jj_consume_token(NUMERO);
emitir("mete " + token.image);
      break;
      }
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
emitir("valord " + token.image);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void expresion() throws ParseException {
    termino();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:
      case MENOS:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAS:{
        jj_consume_token(MAS);
        termino();
emitir("add");
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        termino();
emitir("sub");
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void termino() throws ParseException {
    factor();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR_OP:
      case DIV_OP:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POR_OP:{
        jj_consume_token(POR_OP);
        factor();
emitir("mul");
        break;
        }
      case DIV_OP:{
        jj_consume_token(DIV_OP);
        factor();
emitir("div");
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  final public void factor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUMERO:{
      jj_consume_token(NUMERO);
emitir("mete " + token.image);
      break;
      }
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
emitir("valord " + token.image);
      break;
      }
    case APAREN:{
      jj_consume_token(APAREN);
      expresion();
      jj_consume_token(CPAREN);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void instruccionComparar() throws ParseException {
    jj_consume_token(SI);
    condicion();
    jj_consume_token(ENTONCES);
String lblSino = nuevaEtiqueta();
      String lblFin = nuevaEtiqueta();
      emitir("sifalsovea " + lblSino);
    sentencias();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SINO:{
      jj_consume_token(SINO);
emitir("vea " + lblFin);
      emitir(lblSino + ":");
      sentencias();
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
if (lblFin != null) emitir(lblFin + ":");
      else emitir(lblSino + ":");
    jj_consume_token(FIN_SI);
    jj_consume_token(PUNTO);
}

  final public void instruccionBucle() throws ParseException {
    jj_consume_token(EJECUTA);
String lblInicio = nuevaEtiqueta();
      String lblFin = nuevaEtiqueta();
      emitir(lblInicio + ":");
    sentencias();
    jj_consume_token(FIN_EJECUTA);
    jj_consume_token(HASTA_QUE);
    condicion();
    jj_consume_token(PUNTO);
emitir("not");
      emitir("siciertovea " + lblFin);
      emitir("vea " + lblInicio);
      emitir(lblFin + ":");
}

  final public void condicion() throws ParseException {
    expresion();
    jj_consume_token(ES);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:{
      jj_consume_token(IGUAL);
      jj_consume_token(A);
      expresion();
emitir("xor");
      break;
      }
    case MAYOR:{
      jj_consume_token(MAYOR);
      jj_consume_token(QUE);
      expresion();
emitir("swap");
      emitir("sub");
      break;
      }
    case MENOR:{
      jj_consume_token(MENOR);
      jj_consume_token(QUE);
      expresion();
emitir("sub");
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  /** Generated Token Manager. */
  public CobolCompilerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[15];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x44cf10,0x44cf10,0x4300,0x0,0x0,0x8c10,0x0,0x0,0x0,0x0,0x0,0x0,0x100000,0x70000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x9,0x0,0x0,0x0,0x20,0xf,0x0,0x9,0x180,0x180,0x600,0x600,0x809,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public CobolCompiler(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CobolCompiler(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new CobolCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public CobolCompiler(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CobolCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new CobolCompilerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public CobolCompiler(CobolCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CobolCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 15; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[52];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 15; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 52; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
