/* Generated By:JavaCC: Do not edit this line. CobolCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CobolCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAMA = 1;
  /** RegularExpression Id. */
  int INICIO = 2;
  /** RegularExpression Id. */
  int FIN = 3;
  /** RegularExpression Id. */
  int MUEVE = 4;
  /** RegularExpression Id. */
  int A = 5;
  /** RegularExpression Id. */
  int DE = 6;
  /** RegularExpression Id. */
  int POR = 7;
  /** RegularExpression Id. */
  int LEE = 8;
  /** RegularExpression Id. */
  int MUESTRA = 9;
  /** RegularExpression Id. */
  int SUMA = 10;
  /** RegularExpression Id. */
  int RESTA = 11;
  /** RegularExpression Id. */
  int MULTIPLICA = 12;
  /** RegularExpression Id. */
  int DIVIDE = 13;
  /** RegularExpression Id. */
  int DANDO = 14;
  /** RegularExpression Id. */
  int CALCULA = 15;
  /** RegularExpression Id. */
  int FIN_CALCULA = 16;
  /** RegularExpression Id. */
  int COMO = 17;
  /** RegularExpression Id. */
  int SI = 18;
  /** RegularExpression Id. */
  int ENTONCES = 19;
  /** RegularExpression Id. */
  int SINO = 20;
  /** RegularExpression Id. */
  int FIN_SI = 21;
  /** RegularExpression Id. */
  int EJECUTA = 22;
  /** RegularExpression Id. */
  int FIN_EJECUTA = 23;
  /** RegularExpression Id. */
  int HASTA_QUE = 24;
  /** RegularExpression Id. */
  int VECES = 25;
  /** RegularExpression Id. */
  int USANDO = 26;
  /** RegularExpression Id. */
  int ES = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int MAYOR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int QUE = 31;
  /** RegularExpression Id. */
  int NUMERO = 32;
  /** RegularExpression Id. */
  int CADENA_DOBLE = 33;
  /** RegularExpression Id. */
  int CADENA_SIMPLE = 34;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 35;
  /** RegularExpression Id. */
  int PUNTO = 36;
  /** RegularExpression Id. */
  int COMA = 37;
  /** RegularExpression Id. */
  int IGUAL_ASIGN = 38;
  /** RegularExpression Id. */
  int MAS = 39;
  /** RegularExpression Id. */
  int MENOS = 40;
  /** RegularExpression Id. */
  int POR_OP = 41;
  /** RegularExpression Id. */
  int DIV_OP = 42;
  /** RegularExpression Id. */
  int APAREN = 43;
  /** RegularExpression Id. */
  int CPAREN = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"PROGRAMA\"",
    "\"INICIO\"",
    "\"FIN\"",
    "\"MUEVE\"",
    "\"A\"",
    "\"DE\"",
    "\"POR\"",
    "\"LEE\"",
    "\"MUESTRA\"",
    "\"SUMA\"",
    "\"RESTA\"",
    "\"MULTIPLICA\"",
    "\"DIVIDE\"",
    "\"DANDO\"",
    "\"CALCULA\"",
    "\"FIN-CALCULA\"",
    "\"COMO\"",
    "\"SI\"",
    "\"ENTONCES\"",
    "\"SINO\"",
    "\"FIN-SI\"",
    "\"EJECUTA\"",
    "\"FIN-EJECUTA\"",
    "\"HASTA-QUE\"",
    "\"VECES\"",
    "\"USANDO\"",
    "\"ES\"",
    "\"IGUAL\"",
    "\"MAYOR\"",
    "\"MENOR\"",
    "\"QUE\"",
    "<NUMERO>",
    "<CADENA_DOBLE>",
    "<CADENA_SIMPLE>",
    "<IDENTIFICADOR>",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 49>",
    "<token of kind 50>",
    "<token of kind 51>",
  };

}
