/* CobolCompilerTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. CobolCompilerTokenManager.java */
import java.io.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class CobolCompilerTokenManager implements CobolCompilerConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffdeL) != 0L)
         {
            jjmatchedKind = 35;
            return 8;
         }
         if ((active0 & 0x20000000000L) != 0L)
            return 19;
         if ((active0 & 0x200000000000L) != 0L)
            return 16;
         if ((active0 & 0x20L) != 0L)
            return 8;
         return -1;
      case 1:
         if ((active0 & 0xf7ebff9eL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 35;
               jjmatchedPos = 1;
            }
            return 8;
         }
         if ((active0 & 0x8140040L) != 0L)
            return 8;
         return -1;
      case 2:
         if ((active0 & 0x775afe16L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 35;
               jjmatchedPos = 2;
            }
            return 8;
         }
         if ((active0 & 0x80a10188L) != 0L)
            return 8;
         return -1;
      case 3:
         if ((active0 & 0x77e9fa16L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 3;
            return 8;
         }
         if ((active0 & 0x120400L) != 0L)
            return 8;
         return -1;
      case 4:
         if ((active0 & 0x72004810L) != 0L)
            return 8;
         if ((active0 & 0x5e9b206L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 4;
            return 8;
         }
         return -1;
      case 5:
         if ((active0 & 0x1c99202L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 5;
            return 8;
         }
         if ((active0 & 0x4202004L) != 0L)
            return 8;
         return -1;
      case 6:
         if ((active0 & 0x408200L) != 0L)
            return 8;
         if ((active0 & 0x1891002L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 6;
            return 8;
         }
         return -1;
      case 7:
         if ((active0 & 0x80002L) != 0L)
            return 8;
         if ((active0 & 0x1811000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 7;
            return 8;
         }
         return -1;
      case 8:
         if ((active0 & 0x1000000L) != 0L)
            return 8;
         if ((active0 & 0x811000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 8;
            return 8;
         }
         return -1;
      case 9:
         if ((active0 & 0x1000L) != 0L)
            return 8;
         if ((active0 & 0x810000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
            return 8;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 32:
         return jjStartNfaWithStates_0(0, 45, 16);
      case 40:
         return jjStopAtPos(0, 43);
      case 41:
         return jjStopAtPos(0, 44);
      case 42:
         return jjStartNfaWithStates_0(0, 41, 19);
      case 43:
         return jjStopAtPos(0, 39);
      case 44:
         return jjStopAtPos(0, 37);
      case 45:
         return jjStopAtPos(0, 40);
      case 46:
         return jjStopAtPos(0, 36);
      case 47:
         return jjStopAtPos(0, 42);
      case 61:
         return jjStopAtPos(0, 38);
      case 65:
         return jjStartNfaWithStates_0(0, 5, 8);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x28000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x6040L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x8480000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0xa10008L);
      case 72:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x10000004L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x60001210L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x82L);
      case 81:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x140400L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x2100c000L);
      case 69:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(1, 6, 8);
         return jjMoveStringLiteralDfa2_0(active0, 0x42000900L);
      case 71:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 73:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xb12008L);
      case 74:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x80004L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x20080L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x2L);
      case 83:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(1, 27, 8);
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x80001610L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 69:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 8, 8);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(2, 31, 8);
         return jjMoveStringLiteralDfa3_0(active0, 0x400210L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x9000L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x20400L);
      case 78:
         if ((active0 & 0x8L) != 0L)
         {
            jjmatchedKind = 3;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x40b14000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x2L);
      case 82:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 8);
         break;
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000800L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
      case 86:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 89:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa4_0(active0, 0xa10000L);
      case 65:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 8);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x408004L);
      case 68:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 69:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000L);
      case 79:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 8);
         else if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 8);
         return jjMoveStringLiteralDfa4_0(active0, 0x60080000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x1001800L);
      case 86:
         return jjMoveStringLiteralDfa4_0(active0, 0x10L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 8);
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 68:
         return jjMoveStringLiteralDfa5_0(active0, 0x4002000L);
      case 69:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 4, 8);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x1004L);
      case 76:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 8);
         break;
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L);
      case 79:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(4, 14, 8);
         break;
      case 82:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 8);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 30, 8);
         return jjMoveStringLiteralDfa5_0(active0, 0x2L);
      case 83:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 25, 8);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x408000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x10002L);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000L);
      case 69:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 8);
         break;
      case 73:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 21, 8);
         break;
      case 74:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000L);
      case 79:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(5, 2, 8);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 26, 8);
         break;
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x200L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 9, 8);
         else if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(6, 15, 8);
         else if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(6, 22, 8);
         break;
      case 69:
         return jjMoveStringLiteralDfa7_0(active0, 0x880000L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x11000L);
      case 77:
         return jjMoveStringLiteralDfa7_0(active0, 0x2L);
      case 81:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(7, 1, 8);
         break;
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x810000L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L);
      case 83:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(7, 19, 8);
         break;
      case 85:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000L);
      case 69:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(8, 24, 8);
         break;
      case 85:
         return jjMoveStringLiteralDfa9_0(active0, 0x810000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(9, 12, 8);
         break;
      case 76:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000L);
      case 84:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(10, 16, 8);
         else if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(10, 23, 8);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 25;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 32)
                        kind = 32;
                     { jjCheckNAdd(0); }
                  }
                  else if (curChar == 42)
                     { jjAddStates(0, 1); }
                  else if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if (curChar == 39)
                     { jjCheckNAddTwoStates(5, 6); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 19:
                  if (curChar != 62)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  { jjCheckNAdd(0); }
                  break;
               case 2:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(2, 3); }
                  break;
               case 3:
                  if (curChar == 34 && kind > 33)
                     kind = 33;
                  break;
               case 4:
                  if (curChar == 39)
                     { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 5:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(5, 6); }
                  break;
               case 6:
                  if (curChar == 39 && kind > 34)
                     kind = 34;
                  break;
               case 8:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 9:
                  if (curChar != 42)
                     break;
                  if (kind > 51)
                     kind = 51;
                  { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 10:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 11:
                  if ((0x2400L & l) != 0L && kind > 51)
                     kind = 51;
                  break;
               case 12:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 13:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 42)
                     { jjAddStates(0, 1); }
                  break;
               case 20:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 21:
                  if ((0x2400L & l) != 0L && kind > 49)
                     kind = 49;
                  break;
               case 23:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjAddStates(2, 3); }
                  break;
               case 24:
                  if ((0x2400L & l) != 0L && kind > 50)
                     kind = 50;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 8:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 35)
                     kind = 35;
                  { jjCheckNAdd(8); }
                  break;
               case 19:
                  if (curChar != 124)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 2:
                  { jjAddStates(4, 5); }
                  break;
               case 5:
                  { jjAddStates(6, 7); }
                  break;
               case 10:
                  if (kind > 51)
                     kind = 51;
                  { jjAddStates(8, 9); }
                  break;
               case 20:
                  if (kind > 49)
                     kind = 49;
                  { jjAddStates(10, 11); }
                  break;
               case 23:
                  if (kind > 50)
                     kind = 50;
                  { jjCheckNAddTwoStates(23, 24); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(4, 5); }
                  break;
               case 5:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(6, 7); }
                  break;
               case 10:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  { jjAddStates(8, 9); }
                  break;
               case 20:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  { jjAddStates(10, 11); }
                  break;
               case 23:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  { jjAddStates(2, 3); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 25 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\120\122\117\107\122\101\115\101", "\111\116\111\103\111\117", 
"\106\111\116", "\115\125\105\126\105", "\101", "\104\105", "\120\117\122", "\114\105\105", 
"\115\125\105\123\124\122\101", "\123\125\115\101", "\122\105\123\124\101", 
"\115\125\114\124\111\120\114\111\103\101", "\104\111\126\111\104\105", "\104\101\116\104\117", 
"\103\101\114\103\125\114\101", "\106\111\116\55\103\101\114\103\125\114\101", "\103\117\115\117", "\123\111", 
"\105\116\124\117\116\103\105\123", "\123\111\116\117", "\106\111\116\55\123\111", "\105\112\105\103\125\124\101", 
"\106\111\116\55\105\112\105\103\125\124\101", "\110\101\123\124\101\55\121\125\105", "\126\105\103\105\123", 
"\125\123\101\116\104\117", "\105\123", "\111\107\125\101\114", "\115\101\131\117\122", 
"\115\105\116\117\122", "\121\125\105", null, null, null, null, "\56", "\54", "\75", "\53", "\55", 
"\52", "\57", "\50", "\51", null, null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   19, 22, 23, 24, 2, 3, 5, 6, 10, 11, 20, 21, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

    /** Constructor. */
    public CobolCompilerTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public CobolCompilerTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 25; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, 
};
static final long[] jjtoToken = {
   0x1fffffffffffL, 
};
static final long[] jjtoSkip = {
   0xfe00000000000L, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[25];
    private final int[] jjstateSet = new int[2 * 25];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
